//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWU_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkIND
    {
        public int checkindID { get; set; }
        public int kortlaeserID { get; set; }
        public System.DateTime ckeckIND { get; set; }
        public int antalPersoner { get; set; }
        public bool checkStatus { get; set; }
    }
}
