//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWU_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class omraade
    {
        public int omraadeID { get; set; }
        public string omraadreNavn { get; set; }
        public int rolleID { get; set; }
        public int maxAntal { get; set; }
    }
}
