//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWU_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class personale
    {
        public int personaleID { get; set; }
        public string fornavn { get; set; }
        public string efternavn { get; set; }
        [DisplayName("Brugernavn")]
        [Required(ErrorMessage ="Skal udfyldes")]
        public string brugernavn { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Skal udfyldes")]
        public string password { get; set; }
        public int rolleID { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
